#!/bin/bash

while getopts "f" opt; do
	case "$opt" in
		"f")
			export DOTFILES_FULL=1
			;;
		*)
			echo "Unsupported option. Exiting."
			exit 1
			;;
	esac
done

echo "#########################"
echo "# Beggining instalation #"
echo "#########################"

sudo echo "# Getting password..."

echo "# Pacman"
./packages.sh

echo "# AUR"
./aur.sh

echo "# Linker"
if [[ "$(basename $PWD)" != "dotfiles" ]]; then
	cd ..
fi

(cd headless
for folder in **; do
	stow --restow "$folder"
done)

if [[ -n "$DOTFILES_FULL" ]]; then
	(cd desktop
	for folder in **; do
		stow --restow "$folder"
	done)
fi

echo "# Post instalation things..."
./post.sh

unset DOTFILES_FULL
