#!/bin/bash

while getopts "f" opt; do
	case "$opt" in
		"f")
			export DOTFILES_FULL=1
			;;
		*)
			echo "Unsupported option. Exiting."
			exit 1
			;;
	esac
done

if [[ "$(basename $PWD)" != "dotfiles" ]]; then
	cd "$HOME/dotfiles"
fi

echo "#########################"
echo "# Beggining instalation #"
echo "#########################"

sudo echo "# Getting password..."

echo "# Pacman"
./scripts/packages.sh

echo "# AUR"
./scripts/aur.sh

echo "# Linker"
(cd headless
for folder in *; do
	stow --restow "$folder"
done)

if [[ -n "$DOTFILES_FULL" ]]; then
	(cd desktop
	for folder in *; do
		stow --restow "$folder"
	done)
fi

echo "# Post instalation things..."
./scripts/post.sh

unset DOTFILES_FULL
