# Configuration for Alacritty, the GPU enhanced terminal emulator.

env:
  TERM: alacritty
  WINIT_X11_SCALE_FACTOR: "1"

window:
  dimensions:
    columns: 120
    lines: 30

scrolling:
  history: 10000

font: # {{{
  normal:
    family: Iosevka
    style: Regular

  bold:
    family: Iosevka
    style: Bold

  italic:
    family: Iosevka
    style: Italic

  bold_italic:
    family: Iosevka
    style: Bold Italic

  size: 13.5

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0
# }}}

draw_bold_text_with_bright_colors: false

colors: # {{{
  primary:
    background: '#1d2021'
    foreground: '#ebdbb2'
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'
# }}}

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

cursor:
  style: Block
  #style: Underline
  #style: Beam
  unfocused_hollow: true

shell:
  program: zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"

key_bindings:
  - { key: F11,                           action: ToggleFullscreen }
  - { key: Key0,           mods: Control, action: ResetFontSize    }
  - { key: Equals,         mods: Control, action: IncreaseFontSize }
  - { key: Plus,           mods: Control, action: IncreaseFontSize }
  - { key: NumpadAdd,      mods: Control, action: IncreaseFontSize }
  - { key: Minus,          mods: Control, action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Control, action: DecreaseFontSize }
